plugins {
    id 'java'
}

group = project.findProperty('group') ?: 'com.pvzce'
version = project.findProperty('version') ?: '1.0.0'

allprojects {
    group = rootProject.group
    version = rootProject.version
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.findProperty('java_version') as String)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            events 'failed', 'skipped'
            exceptionFormat 'full'
        }
    }
}
