package com.pvzce.common.level;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.pvzce.api.util.Identifier;

import java.util.List;

/**
 * The four rhythm tiers, as data: the shape of a chart and the levels it is written into.
 *
 * <p>One track, one tempo, four densities. The generator lives in {@code common} rather than in the
 * editor because both sides need the same answer: the editor writes the files with it, and the
 * shipped levels were written with it, so "what a tier is" has one definition - the same reason
 * every other piece of content has a single home.
 *
 * <p>The charts are generated rather than transcribed. A rhythm chart is normally an author's
 * note-by-note work, and this project has no audio analysis to derive one from; what it does have
 * is a tempo and a difficulty, and a deterministic pattern from those two is a chart that can be
 * regenerated byte for byte. That is the honest shape of the feature: the levels are playable, the
 * numbers are the level file's, and a hand-written chart drops into the same block whenever
 * somebody writes one.
 */
public final class RhythmCharts {
    /** How many beats a generated chart runs for. */
    public static final int LENGTH_BEATS = 96;
    /** Where the first beat lands, in ticks: five seconds, which is the build phase's end. */
    public static final int OFFSET_TICKS = 300;

    /**
     * One difficulty.
     *
     * @param suffix      the level file's name and the tier's identity
     * @param displayName what the level list calls it
     * @param bpm         the tier's tempo: the tiers are four speeds of the same track
     * @param density     notes per beat, per lane
     * @param rows        the rows this tier's chart plays
     * @param cols        the columns this tier's chart plays
     * @param waves       the wave table, as raw JSON
     */
    public record Tier(String suffix, String displayName, double bpm, double density,
                       List<Integer> rows, List<Integer> cols, String waves) {
    }

    private static final String ROWS_JSON = "[0,1,2,3,4]";

    private static final String[] WAVES = {
        "[{\"type\":\"small\",\"delay\":2400,\"spawn_interval\":420,\"entries\":["
                + entry("basic_zombie", 3) + "]},"
                + "{\"type\":\"small\",\"delay\":2400,\"spawn_interval\":380,\"entries\":["
                + entry("basic_zombie", 3) + "," + entry("conehead_zombie", 1) + "]},"
                + "{\"type\":\"final\",\"delay\":2600,\"warning_ticks\":750,\"spawn_interval\":320,"
                + "\"entries\":[" + entry("basic_zombie", 4) + "," + entry("conehead_zombie", 2)
                + "]}]",
        "[{\"type\":\"small\",\"delay\":2400,\"spawn_interval\":380,\"entries\":["
                + entry("basic_zombie", 3) + "," + entry("conehead_zombie", 1) + "]},"
                + "{\"type\":\"small\",\"delay\":2300,\"spawn_interval\":340,\"entries\":["
                + entry("conehead_zombie", 2) + "," + entry("buckethead_zombie", 1) + "]},"
                + "{\"type\":\"final\",\"delay\":2600,\"warning_ticks\":750,\"spawn_interval\":280,"
                + "\"entries\":[" + entry("basic_zombie", 4) + "," + entry("conehead_zombie", 2)
                + "," + entry("buckethead_zombie", 1) + "]}]",
        "[{\"type\":\"small\",\"delay\":2300,\"spawn_interval\":340,\"entries\":["
                + entry("conehead_zombie", 2) + "," + entry("buckethead_zombie", 1) + "]},"
                + "{\"type\":\"small\",\"delay\":2200,\"spawn_interval\":300,\"entries\":["
                + entry("conehead_zombie", 2) + "," + entry("pole_vaulter_zombie", 1) + ","
                + entry("buckethead_zombie", 1) + "]},"
                + "{\"type\":\"final\",\"delay\":2500,\"warning_ticks\":750,\"spawn_interval\":240,"
                + "\"entries\":[" + entry("basic_zombie", 4) + "," + entry("conehead_zombie", 2)
                + "," + entry("buckethead_zombie", 2) + "," + entry("football_zombie", 1) + "]}]",
        "[{\"type\":\"small\",\"delay\":2200,\"spawn_interval\":300,\"entries\":["
                + entry("conehead_zombie", 3) + "," + entry("buckethead_zombie", 1) + "]},"
                + "{\"type\":\"small\",\"delay\":2100,\"spawn_interval\":260,\"entries\":["
                + entry("conehead_zombie", 2) + "," + entry("buckethead_zombie", 2) + ","
                + entry("football_zombie", 1) + "]},"
                + "{\"type\":\"final\",\"delay\":2400,\"warning_ticks\":750,\"spawn_interval\":200,"
                + "\"entries\":[" + entry("basic_zombie", 5) + "," + entry("conehead_zombie", 3)
                + "," + entry("buckethead_zombie", 2) + "," + entry("football_zombie", 2) + "]}]",
    };

    /** The four tiers, in the order the level list shows them. */
    public static final Tier[] TIERS = {
        new Tier("easy", "节奏草坪 · 简单", 100D, 0.34, List.of(2), List.of(4), WAVES[0]),
        new Tier("normal", "节奏草坪 · 普通", 110D, 0.5, List.of(1, 3), List.of(2, 6), WAVES[1]),
        new Tier("hard", "节奏草坪 · 困难", 125D, 0.66, List.of(0, 2, 4), List.of(1, 4, 7),
                WAVES[2]),
        new Tier("expert", "节奏草坪 · 专家", 140D, 0.85, List.of(0, 1, 2, 3, 4),
                List.of(0, 2, 4, 6, 8), WAVES[3]),
    };

    private static String entry(String zombie, int count) {
        return "{\"id\":\"pvzce:" + zombie + "\",\"count\":" + count + ",\"rows\":" + ROWS_JSON + "}";
    }

    private RhythmCharts() {
    }

    /**
     * One lane of a generated chart, as the level file writes it.
     *
     * <p>Deterministic in the tier's density and the lane's own index: the notes start half a beat
     * apart down the lanes so the chart is a run rather than a wall, and they step by
     * {@code 1/density} beats so a denser tier is the same tune played faster. Nothing here reads a
     * clock or a random source - the same arguments give the same file, which is what lets a test
     * pin the shipped levels against the generator.
     */
    private static JsonObject lane(String kind, int index, double density, int laneOrdinal) {
        JsonObject lane = new JsonObject();
        lane.addProperty("kind", kind);
        lane.addProperty("index", index);
        JsonArray notes = new JsonArray();
        double step = 1D / Math.max(0.2D, density);
        double beat = 4D + laneOrdinal * 0.5D;
        while (beat < LENGTH_BEATS) {
            notes.add(Math.round(beat * 1000D) / 1000D);
            beat += step;
        }
        lane.add("notes", notes);
        return lane;
    }

    /** The whole level file for one tier, as JSON text. */
    public static String levelJson(Identifier id, String name, String music, double bpm,
                                   double density, List<Integer> rows, List<Integer> cols,
                                   String wavesJson, int damage, int perfectSun) {
        JsonObject root = new JsonObject();
        root.addProperty("id", id.toString());
        root.addProperty("name", name);
        root.addProperty("description", "节奏草坪：谱面按拍走，按对应的键就能让那一行或那一列发动攻击。"
                + "行键 D F G H J，列键 Q W E R Y U I O P；PERFECT 额外掉阳光。"
                + "这一关不能加速——谱面是按关卡自己的拍子写的。");
        root.addProperty("width", 9);
        root.addProperty("height", 5);
        root.add("scene", scene());
        root.add("teams", teams());
        root.addProperty("win_team", "pvzce:plant_team");
        root.add("playable_teams", strings("pvzce:plant_team"));
        root.add("rules", rules());
        root.add("env_vars", new JsonObject());
        root.addProperty("wave_interval_end_multiplier", 1.0D);
        root.add("slots", strings("pvzce:sun", "pvzce:pea_shooter", "pvzce:wall_nut", "pvzce:shovel"));
        root.addProperty("max_seed_slots", 4);
        root.addProperty("seed_screen", false);
        root.addProperty("initial_sun", 250);
        root.add("mechanics", mechanics(bpm, density, rows, cols, damage, perfectSun));
        root.add("waves", com.google.gson.JsonParser.parseString(wavesJson));
        root.add("music", music(music));
        root.addProperty("background", "pvzce:textures/gui/screen/level/background1");
        root.add("hidden_scene_elements", strings("pvzce:grass"));
        root.addProperty("disable_shaders", true);
        root.add("hints", hints());
        root.add("unlock_resources", unlockResources());
        root.add("buffs", strings("pvzce:player_choice"));
        root.add("rewards", rewards());
        return new GsonBuilder().setPrettyPrinting().create().toJson(root);
    }

    private static JsonObject scene() {
        JsonArray cells = new JsonArray();
        for (int y = 0; y < 5; y++) {
            for (int x = 0; x < 9; x++) {
                cells.add(x + "," + y);
            }
        }
        JsonObject scene = new JsonObject();
        scene.add("pvzce:grass", cells);
        return scene;
    }

    private static JsonArray teams() {
        JsonArray teams = new JsonArray();
        teams.add(team("pvzce:plant_team", "植物方", "survive_waves"));
        teams.add(team("pvzce:zombie_team", "僵尸方", "plant_side_lost"));
        return teams;
    }

    private static JsonObject team(String id, String name, String condition) {
        JsonObject team = new JsonObject();
        team.addProperty("id", id);
        team.addProperty("name", name);
        team.addProperty("win_condition", condition);
        return team;
    }

    private static JsonObject rules() {
        JsonObject rules = new JsonObject();
        rules.addProperty("pvzce:day_length", 0);
        rules.addProperty("pvzce:night_length", -1);
        rules.addProperty("pvzce:sun_spawn_interval_min", 0);
        rules.addProperty("pvzce:sun_spawn_interval_max", 0);
        rules.addProperty("pvzce:sun_spawn_initial_ticks", 0);
        rules.addProperty("pvzce:zombie_sun_drop_chance", 0.0D);
        return rules;
    }

    private static JsonArray mechanics(double bpm, double density, List<Integer> rows,
                                       List<Integer> cols, int damage, int perfectSun) {
        JsonArray mechanics = new JsonArray();
        // The build phase is the chart's own buffer: the first note is five seconds away, and the
        // phase is what the player spends those five seconds in (see PreparationData's javadoc).
        JsonObject prep = new JsonObject();
        prep.addProperty("type", "pvzce:preparation");
        prep.addProperty("manual", true);
        prep.addProperty("ticks", 0);
        prep.addProperty("refund", true);
        mechanics.add(prep);

        JsonObject rhythm = new JsonObject();
        rhythm.addProperty("type", "pvzce:rhythm");
        rhythm.addProperty("bpm", bpm);
        rhythm.addProperty("offset_ticks", OFFSET_TICKS);
        rhythm.addProperty("perfect_ticks", 4);
        rhythm.addProperty("good_ticks", 9);
        rhythm.addProperty("perfect_sun", perfectSun);
        rhythm.addProperty("attack_damage", damage);
        JsonArray lanes = new JsonArray();
        int ordinal = 0;
        for (int row : rows) {
            lanes.add(lane("row", row, density, ordinal++));
        }
        for (int col : cols) {
            lanes.add(lane("col", col, density, ordinal++));
        }
        rhythm.add("lanes", lanes);
        mechanics.add(rhythm);
        return mechanics;
    }

    private static JsonObject music(String event) {
        JsonObject cue = new JsonObject();
        cue.addProperty("at_tick", 0);
        cue.addProperty("track", "background");
        cue.addProperty("event", event);
        cue.addProperty("loop", true);
        cue.addProperty("volume", 0.85D);
        cue.addProperty("fade_seconds", 1.0D);
        JsonArray cues = new JsonArray();
        cues.add(cue);
        JsonObject music = new JsonObject();
        music.add("cues", cues);
        return music;
    }

    private static JsonArray hints() {
        JsonArray hints = new JsonArray();
        hints.add(hint("行键 D F G H J，列键 Q W E R Y U I O P：踩上拍子就能打一整行或一整列", 900));
        hints.add(hint("先把阵摆好，再按开始读谱", 900));
        JsonObject refused = new JsonObject();
        refused.addProperty("trigger", "on_card_refused");
        hints.add(refused);
        return hints;
    }

    private static JsonObject hint(String text, int ticks) {
        JsonObject hint = new JsonObject();
        hint.addProperty("trigger", "on_start");
        hint.addProperty("text", text);
        hint.addProperty("duration_ticks", ticks);
        return hint;
    }

    private static JsonObject unlockResources() {
        JsonObject resources = new JsonObject();
        resources.addProperty("pvzce:sun", true);
        return resources;
    }

    private static JsonObject rewards() {
        JsonObject unlock = new JsonObject();
        unlock.addProperty("type", "coins");
        unlock.addProperty("amount", 600);
        JsonArray firstClear = new JsonArray();
        firstClear.add(unlock);
        JsonObject repeat = new JsonObject();
        repeat.addProperty("type", "coins");
        repeat.addProperty("amount", 350);
        JsonArray repeats = new JsonArray();
        repeats.add(repeat);
        JsonObject rewards = new JsonObject();
        rewards.add("first_clear", firstClear);
        rewards.add("repeat", repeats);
        rewards.addProperty("coin_drop", "pvzce:coin_silver");
        rewards.addProperty("coin_drop_chance", 0.25D);
        rewards.addProperty("coin_drop_amount", 1);
        return rewards;
    }

    private static JsonArray strings(String... values) {
        JsonArray array = new JsonArray();
        for (String value : values) {
            array.add(value);
        }
        return array;
    }
}
